### ISSUE TITLE
Handling of Aggregate Types

### ISSUE THREAD

**Issue by aroelke** [IBM/chiffre#14]
It might be useful and/or convenient for Chiffre to be able to handle aggregate types itself, without requiring them to be divided into their members, recursively if required, to get ground types.  I think this would be useful in addition to handling individual members of aggregate types, so users can specify fault injection on entire registers that have fields or on just some of those fields, depending on what they need.

**Comment by seldridge** [comment]
I'm in agreement. Both aggregate injection and injection into a slice of an aggregate should be enabled. If the user has to modify the circuit to enable fault injection, then the whole promise of Chiffre is broken. 

This will be on hold until I get full testing online (#4). I'll include pending tests for these known limitations in the companion PR (#15).

**Comment by aroelke** [comment]
#18

**Comment by aroelke** [comment]
Working on this with PR #18.

**Comment by seldridge** [comment]
Fixed via #18.
