### ISSUE TITLE
Error when try to use Chiffre in a Shifter Register example

### ISSUE THREAD

**Issue by anjianfeng** [IBM/chiffre#30]
I try to apply Chiffre in a shifter register example.

The following attachments are the modified chisel files from Chisel tutorials' file. 

Log message:

sbt:chiffre> testOnly examples.ShiftRegisterTester
[info] [0.002] Elaborating design...
[info] [0.173] Done elaborating.
[info] [0.000] Elaborating design...
[deprecated] Lfsr.scala:78 (1 calls): do_apply is deprecated: "Vec(elts) is deprecated, use VecInit(elts) instead"
[warn] There were 1 deprecated function(s) used. These may stop compiling in a future release - you are encouraged to fix these issues.
[warn] Line numbers for deprecations reported by Chisel may be inaccurate; enable scalac compiler deprecation warnings via either of the following methods:
[warn]   In the sbt interactive console, enter:
[warn]     set scalacOptions in ThisBuild ++= Seq("-unchecked", "-deprecation")
[warn]   or, in your build.sbt, add the line:
[warn]     scalacOptions := Seq("-unchecked", "-deprecation")
[info] [0.072] Done elaborating.
Total FIRRTL Compile Time: 184.5 ms
Total FIRRTL Compile Time: 942.1 ms
[info] ShiftRegisterTester:
[info] ShiftRegister
[info] - should shift a number through a series of registers in firrtl *** FAILED ***
[info]   firrtl.passes.CheckChirrtl$UndeclaredReferenceException: @[:@27.2]: [module ShiftRegister] Reference r0_fault is not declared.
[info]   at firrtl.passes.CheckChirrtl$.checkChirrtlE$1(CheckChirrtl.scala:72)
[info]   at firrtl.passes.CheckChirrtl$.$anonfun$run$20(CheckChirrtl.scala:101)
[info]   at firrtl.ir.DefRegister.mapExpr(IR.scala:224)
[info]   at firrtl.Mappers$StmtMagnet$$anon$2.map(Mappers.scala:19)
[info]   at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[info]   at firrtl.passes.CheckChirrtl$.checkChirrtlS$1(CheckChirrtl.scala:101)
[info]   at firrtl.passes.CheckChirrtl$.$anonfun$run$22(CheckChirrtl.scala:102)
[info]   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[info]   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
[info]   at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
[info]   ...
[info] ScalaTest
[info] Run completed in 1 second, 800 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***

[ShiftRegister.zip](https://github.com/IBM/chiffre/files/3120214/ShiftRegister.zip)

**Comment by seldridge** [comment]
Interesting... and nice test case!

The output for your `ShiftRegister` is below:
```
  module ShiftRegister : @[:@27.2]
    input clock : Clock @[:@28.4]
    input reset : UInt<1> @[:@29.4]
    input io_in : UInt<1> @[:@30.4]
    output io_out : UInt<1> @[:@30.4]
  
    inst r0_injector_ of LfsrInjector32
    inst controller of MyController @[ShiftRegister.scala 42:26:@41.4]
    reg r0 : UInt<1>, clock with :
      reset => (UInt<1>("h0"), r0_fault) @[ShiftRegister.scala 33:19:@32.4]
    reg r1 : UInt<1>, clock with :
      reset => (UInt<1>("h0"), r1) @[ShiftRegister.scala 34:19:@34.4]
    reg r2 : UInt<1>, clock with :
      reset => (UInt<1>("h0"), r2) @[ShiftRegister.scala 35:19:@36.4]
    reg r3 : UInt<1>, clock with :
      reset => (UInt<1>("h0"), r3) @[ShiftRegister.scala 36:19:@38.4]
    node scan_clk = controller.scan_clk
    node r0_injector_io_scan_out = r0_injector_.io_scan_out
    node scan_en = controller.scan_en
    node scan_main_0 = controller.scan_out
    node r0_fault = asUInt(bits(r0_injector_.io_out, 0, 0))
    io_out <= r3 @[ShiftRegister.scala 38:10:@40.4]
    r0_injector_.clock <= clock
    r0_injector_.reset <= reset
    r0_injector_.io_scan_clk <= scan_clk
    r0_injector_.io_scan_en <= scan_en
    r0_injector_.io_scan_in <= scan_main_0
    r0_injector_.io_in <= asUInt(r0)
    r0 <= io_in @[ShiftRegister.scala 33:19:@33.4]
    r1 <= r0_fault @[ShiftRegister.scala 34:19:@35.4]
    r2 <= r1 @[ShiftRegister.scala 35:19:@37.4]
    r3 <= r2 @[ShiftRegister.scala 36:19:@39.4]
    controller.clock <= clock @[:@42.4]
    controller.reset <= reset @[:@43.4]
    controller.scan_main_1 <= r0_injector_io_scan_out
```

The problem is that `r0_fault` is used to initialize `r0`, but `r0_fault` is declared after `r0`. This violates the guarantee of static single assignment (at low or maybe middle FIRRTL) and the compilation dies. 

I'll have to see what's going on, but I'm 90% sure that this is because I'm adding the `node r0_fault` too late in the FIRRTL and this test shows a situation where it needs to be added earlier. Similar to the assumptions that led to https://github.com/freechipsproject/firrtl/issues/749 and the fix https://github.com/freechipsproject/firrtl/pull/823 (more putting these here for my reference).

Thanks again for reporting this and for the test case.

**Comment by anjianfeng** [comment]
How do you get the output?
My output differs from you.
I just put the test case under the Chiffre's src directory. And run command:
sbt "testOnly examples.ShiftRegisterTester"
It seems Chiffre does not work, because no scan chain is generated in ShiftRegister.fir file:

`;buildInfoPackage: chisel3, version: 3.1.7, scalaVersion: 2.12.4, sbtVersion: 1.1.1, builtAtString: 2019-03-20 22:12:35.973, builtAtMillis: 1553119955973
circuit ShiftRegister : 
  module MyController : 
    input clock : Clock
    input reset : UInt<1>
    output io : {}
    
    wire scan : {flip clk : UInt<1>, flip en : UInt<1>, flip in : UInt<1>, out : UInt<1>} @[Instrumentation.scala 37:18]
    scan.in <= UInt<1>("h00") @[Instrumentation.scala 38:11]
    reg clk : UInt<1>, clock @[ShiftRegister.scala 15:16]
    node _T_16 = not(clk) @[ShiftRegister.scala 16:10]
    clk <= _T_16 @[ShiftRegister.scala 16:7]
    scan.clk <= clk @[ShiftRegister.scala 17:12]
    node _T_17 = not(clk) @[ShiftRegister.scala 18:14]
    scan.en <= _T_17 @[ShiftRegister.scala 18:11]
    scan.out <= clk @[ShiftRegister.scala 19:12]
    scan.out <= clk @[ShiftRegister.scala 21:12]
    node _T_18 = eq(scan.in, scan.out) @[ShiftRegister.scala 22:18]
    node _T_19 = bits(reset, 0, 0) @[ShiftRegister.scala 22:9]
    node _T_20 = or(_T_18, _T_19) @[ShiftRegister.scala 22:9]
    node _T_22 = eq(_T_20, UInt<1>("h00")) @[ShiftRegister.scala 22:9]
    when _T_22 : @[ShiftRegister.scala 22:9]
      printf(clock, UInt<1>(1), "Assertion failed\n    at ShiftRegister.scala:22 assert(scan.in === scan.out)\n") @[ShiftRegister.scala 22:9]
      stop(clock, UInt<1>(1), 1) @[ShiftRegister.scala 22:9]
      skip @[ShiftRegister.scala 22:9]
    
  module ShiftRegister : 
    input clock : Clock
    input reset : UInt<1>
    output io : {flip in : UInt<1>, out : UInt<1>}
    
    reg r0 : UInt, clock @[ShiftRegister.scala 33:19]
    r0 <= io.in @[ShiftRegister.scala 33:19]
    reg r1 : UInt, clock @[ShiftRegister.scala 34:19]
    r1 <= r0 @[ShiftRegister.scala 34:19]
    reg r2 : UInt, clock @[ShiftRegister.scala 35:19]
    r2 <= r1 @[ShiftRegister.scala 35:19]
    reg r3 : UInt, clock @[ShiftRegister.scala 36:19]
    r3 <= r2 @[ShiftRegister.scala 36:19]
    io.out <= r3 @[ShiftRegister.scala 38:10]
    inst controller of MyController @[ShiftRegister.scala 42:26]
    controller.clock <= clock
    controller.reset <= reset
    
`

**Comment by anjianfeng** [comment]
How do you get the output?
My output differs from you.
I just put the test case under the Chiffre's src directory. And run command:
sbt "testOnly examples.ShiftRegisterTester"
It seems Chiffre does not work, because no scan chain is generated in ShiftRegister.fir file:

;buildInfoPackage: chisel3, version: 3.1.7, scalaVersion: 2.12.4, sbtVersion: 1.1.1, builtAtString: 2019-03-20 22:12:35.973, builtAtMillis: 1553119955973
circuit ShiftRegister : 
  module MyController : 
    input clock : Clock
    input reset : UInt<1>
    output io : {}
    
    wire scan : {flip clk : UInt<1>, flip en : UInt<1>, flip in : UInt<1>, out : UInt<1>} @[Instrumentation.scala 37:18]
    scan.in <= UInt<1>("h00") @[Instrumentation.scala 38:11]
    reg clk : UInt<1>, clock @[ShiftRegister.scala 15:16]
    node _T_16 = not(clk) @[ShiftRegister.scala 16:10]
    clk <= _T_16 @[ShiftRegister.scala 16:7]
    scan.clk <= clk @[ShiftRegister.scala 17:12]
    node _T_17 = not(clk) @[ShiftRegister.scala 18:14]
    scan.en <= _T_17 @[ShiftRegister.scala 18:11]
    scan.out <= clk @[ShiftRegister.scala 19:12]
    scan.out <= clk @[ShiftRegister.scala 21:12]
    node _T_18 = eq(scan.in, scan.out) @[ShiftRegister.scala 22:18]
    node _T_19 = bits(reset, 0, 0) @[ShiftRegister.scala 22:9]
    node _T_20 = or(_T_18, _T_19) @[ShiftRegister.scala 22:9]
    node _T_22 = eq(_T_20, UInt<1>("h00")) @[ShiftRegister.scala 22:9]
    when _T_22 : @[ShiftRegister.scala 22:9]
      printf(clock, UInt<1>(1), "Assertion failed\n    at ShiftRegister.scala:22 assert(scan.in === scan.out)\n") @[ShiftRegister.scala 22:9]
      stop(clock, UInt<1>(1), 1) @[ShiftRegister.scala 22:9]
      skip @[ShiftRegister.scala 22:9]
    
  module ShiftRegister : 
    input clock : Clock
    input reset : UInt<1>
    output io : {flip in : UInt<1>, out : UInt<1>}
    
    reg r0 : UInt, clock @[ShiftRegister.scala 33:19]
    r0 <= io.in @[ShiftRegister.scala 33:19]
    reg r1 : UInt, clock @[ShiftRegister.scala 34:19]
    r1 <= r0 @[ShiftRegister.scala 34:19]
    reg r2 : UInt, clock @[ShiftRegister.scala 35:19]
    r2 <= r1 @[ShiftRegister.scala 35:19]
    reg r3 : UInt, clock @[ShiftRegister.scala 36:19]
    r3 <= r2 @[ShiftRegister.scala 36:19]
    io.out <= r3 @[ShiftRegister.scala 38:10]
    inst controller of MyController @[ShiftRegister.scala 42:26]
    controller.clock <= clock
    controller.reset <= reset

**Comment by seldridge** [comment]
Yeah, printing internally and not looking at the output. I made this small modification (for debugging):

```diff
diff --git a/src/main/scala/chiffre/passes/FaultInstrumentation.scala b/src/main/scala/chiffre/passes/FaultInstrumentation.scala
index 7444e32..2871dff 100644
--- a/src/main/scala/chiffre/passes/FaultInstrumentation.scala
+++ b/src/main/scala/chiffre/passes/FaultInstrumentation.scala
@@ -75,6 +75,7 @@ class FaultInstrumentation(compMap: Map[String, Seq[(ComponentName, String, Clas
         case ((m, a), (_, Modifications(_,_,mm,aa,_))) => (m ++ mm, a ++ aa) }
 
     val mx = state.circuit.modules map onModule(modifications)
+    mx.map(x => println(x.serialize))
     val cx = ToWorkingIR.run(state.circuit.copy(modules = mxx ++ mx))
 
     val inAnno: Seq[Annotation] = state.annotations.toSeq
```

**Comment by seldridge** [comment]
Alright, I see what's going on and I think I have a fix in mind.

A register is given a default reset initialization value of itself, i.e., you wind up with a chunk like:

```
reg reg : UInt<1>, clock with :
  reset => (reset, reg)
```

The Chiffre transform adds a wire, `reg_faulty`. It then blindly replaces all references to `reg` with `reg_faulty`. One of the replacements that it makes is to that reset value, i.e.:

```
reg reg : UInt<1>, clock with :
  reset => (reset, reg_faulty)
```

I don't think that this is right. Specifically, I don't think that the reset initialization value should be messed with. I can make a PR that corrects this.

In the mean time you can kludge around this by using explicit `RegInit` for registers that you want to inject into. Try something like the following:

```scala
  val regs: Seq[UInt] = Seq.fill(4)(RegInit(0.U))

  regs.foldLeft(io.in){ case (a, b) => b := a; b }
  io.out := regs.last

  val scanId = "main"
  isFaulty(regs(0), scanId, classOf[LfsrInjector32])
  val controller = Module(new MyController(scanId))
```

**Comment by seldridge** [comment]
On second thought, I think that the replacement is correct... this is a FIRRTL bug :sad:. Filing an issue about it: https://github.com/freechipsproject/firrtl/issues/1077

**Comment by anjianfeng** [comment]
Thank you very much for your explanation.
I think I should read Chiffre's implementation in detail.
I also write another simple example for testing Chiffre using a Counter:
https://github.com/anjianfeng/chiffreExample
